number1=input("any number : ")
number2=input("any number : ")
number3=input("any number : ")
number4=input("any number : ")
number5=input("any number : ")
print(number1,+ number2,+ number3,+ number4,+ number5 / 5)